USE [DB_TechNesis_Pruebas]
GO

-- Eliminar la tabla si ya existe
IF OBJECT_ID('dbo.T_ATENCIONES_SIS', 'U') IS NOT NULL
    DROP TABLE dbo.T_ATENCIONES_SIS;
GO

CREATE TABLE T_ATENCIONES_SIS
(
AÑO VARCHAR(10),
MES VARCHAR(5),
REGION VARCHAR(100),
PROVINCIA VARCHAR(100),
UBIGEO_DISTRITO VARCHAR(15),
DISTRITO VARCHAR(100),
COD_UNIDAD_EJECUTORA VARCHAR(10),
DESC_UNIDAD_EJECUTORA VARCHAR(100),
COD_IPRESS VARCHAR(20),
IPRESS VARCHAR(100),
NIVEL_EESS VARCHAR(10),
PLAN_SEGURO VARCHAR(40),
COD_SERVICIO VARCHAR(10),
DESC_SERVICIO VARCHAR(100),
SEXO VARCHAR(25),
GRUPO_EDAD VARCHAR(25),
ATENCIONES INT
);
GO

